# v2 script (owner 2026-10-10 20:57 CST: long videos at least 15 min). Gemini Iapetus reads display text directly.
# Facts checked against: en.wikipedia.org Cryptanalysis_of_the_Enigma, Enigma_machine, Cipher_Bureau_(Poland), Kerckhoffs's_principle;
# tnmoc.org/bombe (211 bombes, 1,676 Wrens); GCHQ Pyry PDF (25-26 July 1939); bl.uk Polish mathematicians blog.
import json
P = [
# ---- cold open
("hook", "During the war, a young codebreaker named Mavis Lever picked up an intercepted Enigma message and noticed something strange. Not a word that was there. A letter that wasn't. In the whole message, there was not a single L."),
("hook", "That absence told her almost exactly what the message said. And it points to the strangest weakness of the machine Germany trusted with its secrets. To see how a missing letter can be a clue, we have to go back to the moment secrets started flying through the air."),
# ---- origins (new)
("origins", "Radio changed war. An order sent by radio reaches a ship or a tank in seconds. But it also reaches anyone else who is listening. Every message an army sends is, in effect, a letter left open on a table. So the real question was never how to stop the enemy hearing. It was how to make what they hear useless."),
("origins", "The oldest tricks were substitutions: swap every A for a Q, every B for an M, and so on. They break easily. In German or English, some letters, like E, are far more common than others, so the most frequent symbol in a long message is probably E. Count enough letters, and the disguise falls apart. Codebreakers had used that idea, frequency analysis, for over a thousand years."),
("origins", "At the end of the First World War, a German engineer named Arthur Scherbius had a better idea: a machine that changes the substitution after every single letter. His company patented the design in 1918 and began selling it in 1923, under a name that promised exactly what it did. Enigma. The German Navy adopted a version in 1926, and the army and air force soon followed."),
# ---- machine
("machine", "Enigma looked like a typewriter in a wooden case. You pressed a key, and instead of printing, a small lamp lit up a different letter. One person typed, another wrote down the glowing letters, and a radio operator sent the result in Morse code."),
("machine", "Inside, the signal ran through three rotors, chosen from a box of five. Each rotor was a wheel with twenty-six contacts on each face, wired in a scrambled pattern. And every time a key was pressed, the right-hand rotor turned one step, like a car's odometer. So the same letter came out differently each time. Press A five times, and you might get five different letters. Counting letters, the old trick, suddenly found nothing to count."),
("machine", "At the front sat a plugboard, where cables swapped pairs of letters before and after the rotors. Count every choice: which rotors, in what order, their starting positions, and ten plug cables. The army version had about one hundred and fifty-nine quintillion possible starting settings. And the settings changed every day, printed on secret key sheets that told every operator how to set up his machine that morning."),
# ---- mirror
("mirror", "But the most important part sat at the far end: a fixed wheel called the reflector. The current went in through the plugboard, through all three rotors, hit the reflector, and came back out through the rotors by a different path."),
("mirror", "It was a clever convenience. Because the path works like a mirror, the machine undoes itself. If A became G, then with the same settings, G became A. The receiver needed no separate decoding mode. Set the same settings, type the scrambled text, and the original message lights up."),
("mirror", "But a mirror has a blind spot. The current could never come back out on the wire it went in on. So no letter could ever be encrypted as itself. A is never A. It sounds like a tiny detail. Yet it meant Enigma's output was not truly random. It leaked one fact, every single time. Hold on to that fact. It will come back to matter enormously."),
# ---- poland
("poland", "The first people to break Enigma were not British. In December 1932, a twenty-seven-year-old mathematician named Marian Rejewski, working for Poland's Cipher Bureau, attacked it with permutation theory, the mathematics of shuffles."),
("poland", "He found his opening in a procedure, not in the machine. Each message began with a three-letter key chosen by the operator, and to guard against radio errors, it was typed twice. Six letters, encrypted at six consecutive rotor positions, but hiding the same three letters. That repetition tied the first letter to the fourth, the second to the fifth, and the third to the sixth."),
("poland", "Collect enough messages from a single day, and those links form chains of letters that loop back on themselves, like a shuffled deck that returns to its start. Rejewski realised that the lengths of those loops depend only on the rotors, not on the plugboard. The plugboard, the part that added most of the complexity, could be set aside."),
("poland", "French intelligence also passed him documents from a German spy, Hans-Thilo Schmidt, including some daily settings. Combining them with his equations, Rejewski worked out the internal wiring of the rotors without ever seeing a military machine. With his colleagues Jerzy Różycki and Henryk Zygalski, the Bureau read Enigma traffic for years, using a huge card catalogue of loop patterns, perforated sheets, and machines they called bombas."),
("poland", "Then Germany made it harder. In December 1938, two extra rotors raised the possible rotor orders from six to sixty. Poland lacked the resources to keep up. So in late July 1939, five weeks before the war began, the Poles met British and French codebreakers in a forest outside Warsaw, and handed over their methods and copies of the machine."),
# ---- escape (new)
("escape", "Weeks later, Germany invaded Poland. The codebreakers escaped through Romania to France, where they kept attacking Enigma at a secret French station. Their story did not end gently. Jerzy Różycki died in 1942, when the ship carrying him back to France sank in the Mediterranean. Rejewski and Zygalski eventually reached Britain, but they were never brought into Bletchley Park, the place that built on their work."),
# ---- crib
("crib", "Bletchley Park was a country house northwest of London, where thousands of people would eventually work in secret. Among them was a young mathematician named Alan Turing. By then, the Germans had also stopped repeating the message key, so the Polish loop trick faded. No machine could check quintillions of settings one by one. The codebreakers needed a new shortcut. They found it in human habits."),
("crib", "German messages were full of routine. Weather reports. Standard phrases, like 'keine besonderen Ereignisse': nothing to report. If you could guess a phrase that probably appeared in a message, you had a crib, a piece of the original text. The only question was where it sat."),
("crib", "This is where the blind spot pays off. Slide the guessed phrase along the scrambled text. Wherever any letter of the guess lands on the same letter in the ciphertext, that position is impossible, because no letter can encrypt to itself. Positions fall away one after another, until only a few remain."),
# ---- bombe
("bombe", "A crib in the right place gives a chain of letter pairs: this letter became that one, at this step. Turing realised the pairs could be linked into loops, and that a wrong rotor setting would make those loops contradict themselves. So he designed a machine to hunt for settings without contradictions: the Bombe."),
("bombe", "Gordon Welchman added a crucial improvement, the diagonal board, which used another German convenience: plugboard swaps work both ways. The first Bombe, named Victory, arrived at Bletchley Park in March 1940. By the end of the war there were about two hundred and eleven, run around the clock, mostly by women of the Women's Royal Naval Service."),
("bombe", "Each Bombe weighed about a ton and carried a hundred and eight rotating drums, in thirty-six sets of three, each set imitating one Enigma. It chattered through rotor positions, rejecting the impossible at electrical speed. When it stopped, it offered a candidate setting. Codebreakers then tested it on a copy of Enigma. If German words appeared, the day's key for that network was broken, and its messages could be read."),
# ---- habits (new)
("habits", "Human habits helped in smaller ways too. Operators were supposed to choose random message keys. Tired people don't. Some typed three neighbouring keys on the keyboard, or the same letters again and again. Bletchley called these slips cillies, and kept careful lists of every lazy pattern they found."),
("habits", "A twenty-one-year-old recruit named John Herivel went further. He imagined an operator setting up his machine first thing in the morning, in a hurry, and guessed that the first messages of the day would start with the rotors sitting close to that day's ring settings. Herivel's tip, together with the cillies, became the main way into Enigma for a brief but critical period after May 1940."),
# ---- shark (new)
("shark", "The hardest target was the Atlantic. German U-boats hunted Allied convoys, and the naval Enigma was used with far stricter discipline. Here, mathematics needed help from the sea. In May 1941, a British boarding party took codebooks from the captured submarine U-110. Material like that turned impossible problems into merely difficult ones."),
("shark", "Then, on the first of February 1942, the U-boats switched to a new machine with a fourth rotor. Bletchley called the traffic Shark, and for most of that year it went dark. The break came only after sailors recovered a weather codebook from the sinking submarine U-559 in October. By December 1942, Shark was being read again. Even then, the crack depended on the same idea: predictable text, and a machine that could never turn a letter into itself."),
# ---- lever
("lever", "Which brings us back to Mavis Lever and the message with no L. She worked in Dilly Knox's team, on the Enigma used by the Italian Navy. That operator had been told to send a dummy message. As she later recalled, he simply pressed the last key on the keyboard, L, over and over."),
("lever", "Every letter of the ciphertext could be anything except L. So the one missing letter gave the whole message away: L, L, L, L, all the way through. She called it the biggest crib they ever had, and it revealed the wiring of a new rotor. One lazy minute, plus one design convenience, opened the machine."),
# ---- secret (new)
("secret", "Then came something almost as remarkable as the breaking itself: silence. After the war, the people of Bletchley Park kept their work secret for decades. Enigma machines stayed in use in some countries into the nineteen-sixties. The break was not made public until 1974, and many codebreakers went to their graves without telling their families what they had done."),
# ---- turing (new, links to the channel's AI pillar)
("turing", "Alan Turing had imagined machines long before the Bombe. In 1936, he described a universal machine: one device that could carry out any procedure that can be written down as a list of steps. After the war, he drew up a design for one of the first stored-program computers, and in 1950 he asked a question that still shapes artificial intelligence today: can machines think?"),
("turing", "His own story ended in tragedy. In 1952 he was prosecuted for being gay, and he died in 1954, at forty-one. Decades later, in 2013, he received a royal pardon, and today his face is on Britain's fifty-pound note. The man who helped read the enemy's secrets lived much of his life forced to keep his own."),
# ---- lesson
("lesson", "Historians still debate exactly how much these intercepts changed the war, though many argue the intelligence known as Ultra shortened it. What is clear is how Enigma fell. Not by brute force alone, but through its structure: a reflector that made one outcome impossible, and people who repeated themselves."),
("lesson", "In 1883, the cryptographer Auguste Kerckhoffs wrote a rule that security engineers still follow: a cipher should stay safe even if the enemy knows exactly how the machine works. Only the key should be secret. Enigma's designers trusted the key. But the machine's own structure leaked information, whatever the key was."),
("lesson", "In a well-designed modern cipher, such as AES, the output looks like random noise. Any symbol can turn into any other, including itself. That is the quiet lesson of Enigma. A pattern doesn't have to be something that appears. Sometimes, the clue is what can never appear."),
("close", "So the next time something looks perfectly random, ask what it never does. This is Latoon. Voyaging the unseen."),
]
S = [[a, b, b] for a, b in P]
json.dump(S, open("script_v2.json", "w"), indent=1, ensure_ascii=False)
print(len(S), "paras", sum(len(x[1].split()) for x in S), "words")
