import json
# [section, VO text (phonetic for TTS where needed), display text (SRT / captions)]
P = [
("hook", "During the war, a young codebreaker named Mavis Lever picked up an intercepted Enigma message and noticed something strange. Not a word that was there. A letter that wasn't. In the whole message, there was not a single L.", None),
("hook", "That absence told her almost exactly what the message said. And it points to the strangest weakness of the machine Germany trusted with its secrets. To see how a missing letter can be a clue, we have to open the box.", None),
("machine", "Enigma looked like a typewriter in a wooden case. You pressed a key, and instead of printing, a small lamp lit up a different letter. One person typed, another wrote down the glowing letters, and a radio operator sent the result in Morse code.", None),
("machine", "Inside, the signal ran through three rotors, chosen from a box of five. Each rotor was a wheel with twenty-six contacts on each face, wired in a scrambled pattern. And every time a key was pressed, the right-hand rotor turned one step, like a car's odometer. So the same letter came out differently each time. Press A five times, and you might get five different letters.", None),
("machine", "At the front sat a plugboard, where cables swapped pairs of letters before and after the rotors. Count every choice: which rotors, in what order, their starting positions, and ten plug cables. The army version had about one hundred and fifty-nine quintillion possible starting settings. And the settings changed every day.", None),
("mirror", "But the most important part sat at the far end: a fixed wheel called the reflector. The current went in through the plugboard, through all three rotors, hit the reflector, and came back out through the rotors by a different path.", None),
("mirror", "It was a clever convenience. Because the path works like a mirror, the machine undoes itself. If A became G, then with the same settings, G became A. The receiver needed no separate decoding mode. Set the same settings, type the scrambled text, and the original message lights up.", None),
("mirror", "But a mirror has a blind spot. The current could never come back out on the wire it went in on. So no letter could ever be encrypted as itself. A is never A. It sounds like a tiny detail. Yet it meant Enigma's output was not truly random. It leaked one fact, every single time.", None),
("poland", "The first people to break Enigma were not British. In December 1932, a twenty-seven-year-old mathematician named Marian Rejefski, working for Poland's Cipher Bureau, attacked it with permutation theory, the mathematics of shuffles.",
 "The first people to break Enigma were not British. In December 1932, a twenty-seven-year-old mathematician named Marian Rejewski, working for Poland's Cipher Bureau, attacked it with permutation theory, the mathematics of shuffles."),
("poland", "French intelligence passed him documents from a German spy, Hans Teelo Schmidt, including some daily settings. Combining them with clever equations, Rejefski worked out the internal wiring of the rotors without ever seeing a military machine. With his colleagues Yezhy Roozhitski and Henrik Zigalski, the Bureau read Enigma traffic for years, using card catalogues, perforated sheets, and machines they called bombas.",
 "French intelligence passed him documents from a German spy, Hans-Thilo Schmidt, including some daily settings. Combining them with clever equations, Rejewski worked out the internal wiring of the rotors without ever seeing a military machine. With his colleagues Jerzy Różycki and Henryk Zygalski, the Bureau read Enigma traffic for years, using card catalogues, perforated sheets, and machines they called bombas."),
("poland", "Then Germany made it harder. In December 1938, two extra rotors raised the possible rotor orders from six to sixty. Poland lacked the resources to keep up. So in July 1939, five weeks before the war began, the Poles handed their methods, and copies of the machine, to the British and the French.", None),
("crib", "The work moved to Bletchley Park, a country house northwest of London, where thousands of people would eventually work in secret. Among them was a young mathematician named Alan Turing. No machine could check quintillions of settings one by one. The codebreakers needed a shortcut. They found it in human habits.", None),
("crib", "German messages were full of routine. Weather reports. Standard phrases, like kyna buh-zonderen er-eye-gnissa: nothing to report. If you could guess a phrase that probably appeared in a message, you had a crib, a piece of the original text. The only question was where it sat.",
 "German messages were full of routine. Weather reports. Standard phrases, like 'keine besonderen Ereignisse': nothing to report. If you could guess a phrase that probably appeared in a message, you had a crib, a piece of the original text. The only question was where it sat."),
("crib", "This is where the blind spot pays off. Slide the guessed phrase along the scrambled text. Wherever any letter of the guess lands on the same letter in the ciphertext, that position is impossible, because no letter can encrypt to itself. Positions fall away one after another, until only a few remain.", None),
("bombe", "A crib in the right place gives a chain of letter pairs: this letter became that one, at this step. Turing realised the pairs could be linked into loops, and that a wrong rotor setting would make those loops contradict themselves. So he designed a machine to hunt for settings without contradictions: the Bombe.", None),
("bombe", "Gordon Welchman added a crucial improvement, the diagonal board, which used another German convenience: plugboard swaps work both ways. The first Bombe, named Victory, arrived at Bletchley Park in March 1940. Many more followed, run around the clock, largely by women of the Women's Royal Naval Service.", None),
("bombe", "Each Bombe chattered through rotor positions, rejecting the impossible at electrical speed. When it stopped, it offered a candidate setting. Codebreakers then tested it on a copy of Enigma. If German words appeared, the day's key for that network was broken, and its messages could be read.", None),
("lever", "Which brings us back to Mavis Lever and the message with no L. She worked in Dilly Knox's team, on the Enigma used by the Italian Navy. That operator had been told to send a dummy message. As she later recalled, he simply pressed the last key on the keyboard, L, over and over.", None),
("lever", "Every letter of the ciphertext could be anything except L. So the one missing letter gave the whole message away: L, L, L, L, all the way through. She called it the biggest crib they ever had, and it revealed the wiring of a new rotor. One lazy minute, plus one design convenience, opened the machine.", None),
("lesson", "Historians still debate exactly how much these intercepts changed the war, though many argue the intelligence known as Ultra shortened it. What is clear is how Enigma fell. Not by brute force alone, but through its structure: a reflector that made one outcome impossible, and people who repeated themselves.", None),
("lesson", "In 1883, the cryptographer Auguste Kerkoffs wrote a rule that security engineers still follow: a cipher should stay safe even if the enemy knows exactly how the machine works. Only the key should be secret. Enigma's designers trusted the key. But the machine's own structure leaked information, whatever the key was.",
 "In 1883, the cryptographer Auguste Kerckhoffs wrote a rule that security engineers still follow: a cipher should stay safe even if the enemy knows exactly how the machine works. Only the key should be secret. Enigma's designers trusted the key. But the machine's own structure leaked information, whatever the key was."),
("lesson", "In a well-designed modern cipher, such as AES, the output looks like random noise. Any symbol can turn into any other, including itself. That is the quiet lesson of Enigma. A pattern doesn't have to be something that appears. Sometimes, the clue is what can never appear.", None),
("close", "So the next time something looks perfectly random, ask what it never does. Latoon. Voyaging the unseen.", None),
]
S = [[a, b, c or b] for a, b, c in P]
json.dump(S, open("script.json", "w"), indent=1)
print(len(S), "paras", sum(len(x[1].split()) for x in S), "words")
